description = """
Image Convolver is a API which classifies images by camera scene
and groups faces by similarity, building a mapping between
people and a set of images with similar faces.

## Face

Read and Update person-face mappings. Face detection is powered by `dlib` and the FaceNet model. Face similarity uses Hierarchical Clustering to group a collection of face encodings generated by the FaceNet model. Supports basic CRUD operations
on People and Images.

## Scene Classification

Classifies images into one of 35 camera photo scenes: 
airplane, animals, baby, beach, bike, bird, bridge, building, cake, car, cat, child, coast, dance, dog, family, flower, food, forest, fruit, holiday, house, lake, landmark, meme, mountain, nature, night, painting, portrait, road, sky, snow, sports, sunset, text document.
"""

tags_metadata = [
    {
        "name": "Face",
        "description": """Read and Update person-face mappings. Uses Face detection similarity methods to group a collection of face data generated by a neural network. Supports CRUD operations on People and Images.""",
    },
    {
        "name": "Scene Classification",
        "description": "Classifies images into one of 35 camera photo scenes.",
    },
]

options = {
    "title": "Image Convolver",
    "openapi_tags": tags_metadata,
    "description": description,
    "version": "1.1.0",
    "terms_of_service": "http://example.com/terms/",
    "license_info": {
        "name": "Apache 2.0",
        "url": "https://www.apache.org/licenses/LICENSE-2.0.html",
    }
}